name: FlyScan

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy=1.24*
  - scikit-image
  - matplotlib-base
  - pip
  # conda_spec
  - jupyterlab
  - napari
  - pyqt
  - pip:
    # pip_core
    # pip_spec